--------------------------------------------------------
--  File created - Wednesday-July-10-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure PROC_BILL4API
--------------------------------------------------------
set define off;

  CREATE OR REPLACE  PROCEDURE "DISCO"."PROC_BILL4API" (
TS VARCHAR2,
KWH NUMBER,
S_PERIOD VARCHAR2,
E_PERIOD VARCHAR2,
TRF VARCHAR2,
ED_CD VARCHAR2,
SEASON_CHRG NUMBER,
STD_CLSF_CD VARCHAR2,
GST_EXMT_CD VARCHAR2,
FIX_CHARGE NUMBER,
METER_RENT NUMBER,
SRV_RENT NUMBER,
DSSUR NUMBER,
UOSUR NUMBER,
NO_OF_TV NUMBER,
FATA_PATA_CD VARCHAR2,
P_TOT_CONS NUMBER,
V_ED OUT NUMBER,
V_ENERGY OUT NUMBER,
V_GST OUT NUMBER,
V_ITAX OUT NUMBER,
V_PTVFEE OUT NUMBER,
V_EQSUR OUT NUMBER,
V_NJSUR OUT NUMBER
)
IS

mon_diff NUMBER;

BEGIN
    
BEGIN
    SELECT ENRCHRG
    INTO V_ENERGY
    FROM TABLE(GETVW_ENRG_TR_TABLE(TS, KWH, S_PERIOD, E_PERIOD,TRF));
EXCEPTION
WHEN OTHERS THEN
    V_ENERGY:=0;
END;

BEGIN
SELECT CAST(MONTHS_BETWEEN (E_PERIOD,S_PERIOD) AS INT) INTO mon_diff  FROM DUAL;  
END;

BEGIN
    SELECT EQSUR
    INTO V_EQSUR
    FROM TABLE(GETEQSUR(V_ENERGY, TRF, KWH, S_PERIOD, E_PERIOD, mon_diff));
EXCEPTION
WHEN OTHERS THEN
    V_EQSUR:=0;
END;



BEGIN 
    SELECT ED 
    INTO V_ED 
    FROM TABLE(GETED(ED_CD, V_ENERGY, V_EQSUR, SEASON_CHRG, TRF, s_period, e_period));
EXCEPTION
WHEN OTHERS THEN
    V_ED:=0;
END;

BEGIN
    SELECT GST_CHARGES
    INTO V_GST
    FROM TABLE(GETGSTCHARGES(TRF, STD_CLSF_CD, ED_CD, GST_EXMT_CD, V_ENERGY, FIX_CHARGE, V_EQSUR, V_ED, METER_RENT, SRV_RENT,
    DSSUR, UOSUR, S_PERIOD, E_PERIOD, KWH));
EXCEPTION
WHEN OTHERS THEN   
    V_GST:=0;
END;

BEGIN
    SELECT NJSUR
    INTO V_NJSUR
    FROM TABLE(GETNJSUR(KWH, TRF, S_PERIOD, E_PERIOD, mon_diff, P_TOT_CONS));
EXCEPTION
WHEN OTHERS THEN
    V_NJSUR:=0;
END;

BEGIN
    SELECT * 
    INTO V_ITAX
    FROM TABLE(GETITAX(V_GST + V_ENERGY,V_GST + V_ENERGY, TRF, S_PERIOD, E_PERIOD, mon_diff)); 
EXCEPTION
WHEN OTHERS THEN   
    V_ITAX:=0;    
END;

BEGIN 
    SELECT PTV_FEE 
    INTO V_PTVFEE 
    FROM TABLE(GETPTVFEE(NO_OF_TV, TRF, STD_CLSF_CD, ED_CD, FATA_PATA_CD, S_PERIOD, E_PERIOD, mon_diff));
    
EXCEPTION
WHEN OTHERS THEN   
    V_PTVFEE:=0;
END;

--DBMS_OUTPUT.PUT_LINE('ED :  ' || V_ED);
--DBMS_OUTPUT.PUT_LINE('ENERGY :  ' || V_ENERGY);
--DBMS_OUTPUT.PUT_LINE('GST :  ' || V_GST);
--DBMS_OUTPUT.PUT_LINE('ITAX  : ' || V_ITAX);
--DBMS_OUTPUT.PUT_LINE('PTV FEE  : ' || V_PTVFEE);

END;

/
